name: Pull Request Merge

on:
    pull_request:
        - closed

jobs:
    correct_tag:
        name: 'Ensure tagged correctly'
        if: github.event.pull_request.merged == 'true'
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: actions-ecosystem/action-add-labels@v1
              if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
                with:
                    labels: hacktoberfest-accepted